name: flutter_hive_tdo
description: Flutter Hive Todo app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  uuid: ^4.2.2
  intl: ^0.19.0
  #flutter_datetime_picker: ^2.1.0
  animate_do: ^3.1.2
  flutter_beautiful_popup: ^1.7.0
  panara_dialogs: ^0.1.2
  lottie: ^2.7.0
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  meta: ^1.10.0
  connectivity_plus: ^5.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
